word-lists:
      wordListOne:
      - "круглосуточный"
      - "трех-звенный"
      - "взаимный"
      - "динамический"
      wordListTwo:
      - "фирменный"
      - "сетевой"
      - "ускоренный"
      - "использованый с выгодой"
      wordListThree:
      - "процесс"
      - "подход"
      - "портал"
      - "уровень завоевоного внимания"
      - "обзор"
      - "выход из положения"
